[font]
size = 14.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]
